server:
  port: 8080

spring:
  datasource:
    driver-class-name: ${DB_DRIVER_CLASS}
    url: ${DB_URL}
    username: ${USERNAME}
    password: ${PASSWORD}

  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: update
    show-sql: true

jwt:
  access-secret: ${ACCESS_SECRET}
  refresh-secret: ${REFRESH_SECRET}
  access-expiration: 86400000
  refresh-expiration: 604800000

cloud:
  aws:
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
    region: ${S3_REGION}
    S3:
      bucket: ${S3_BUCKET_NAME}

coolsms:
  api:
    key: ${SMS_KEY}
    secret: ${SMS_SECRET_KEY}
    phoneNumber: ${SMS_PHONE_NUMBER}

ai-server:
  base-url: ${AI_SERVER_BASE_URL}
